apiVersion: v1
kind: Pod
metadata:
  name: devops-kubernetes-hw-nginx
  namespace: default
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx:1.20
      livenessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
      ports:
      - name: http
        containerPort: 80
        protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-kubernetes-hw-image
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: devops-kubernetes-hw-image
        image: docker_hw1
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: devops-kubernetes-hw-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    app: web
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001